# Pipeline configuration to produce influenza univariate models

run_type: "univariate_prod"

write: TRUE
wipe: FALSE
earliest_date: "2022-08-01"


output_bucket: "PATH REMOVED/data/pancast_pipeline/rsv"


sources:
  total_beds:
    include: TRUE
    path:
    path_type:
    pattern:
  rsv_beds:
    include: TRUE
    path:
    path_type:
    pattern:
  rsv_inpatient_tests:
    include: TRUE
    path: "PATH REMOVED/data/SGSS/winter_pressures/"
    path_type: "dynamic"
    pattern: "sgss_winter_pressure_"
