# Pipeline configuration to produce univariate models

run_type: "univariate_prod"

write: TRUE
wipe: FALSE
earliest_date: "2021-01-01"


output_bucket: "PATH REMOVED/data/pancast_pipeline/covid"


sources:
  total_beds:
    include: TRUE
    path:
    path_type:
    pattern:
  covid_beds:
    include: TRUE
    path:
    path_type:
    pattern:
